model:
  base_model: "yolo11n.pt"  # Base YOLOv11 model file
  trained_model_dir: "trained_models/yolov11"
  trained_model_name: "best.pt"

training:
  data: "datasets/balloons/dataset.yaml"
  epochs: 150
  imgsz: 640
  batch: 128
  workers: 4
